//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSSWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class serie
    {
        public int time { get; set; }
        public Nullable<int> esempio { get; set; }
        public Nullable<double> esempio2 { get; set; }
        public Nullable<int> Passengers { get; set; }
        public Nullable<int> jewelry { get; set; }
    }
}
